name: Repo2
on:
  repository_dispatch:
    types: [hello]
 
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  Repo2:
    name: Repo2
    environment: ${{ github.event.client_payload.env }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Echo ${{ github.event.client_payload.env }} environment
        run: echo Repo2 ${{ github.event.client_payload.env }}

      
