name: test
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
      

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    name: run task
    uses: RTC12-Test/golang1/.github/workflows/test.yml@main
    with:
      REPO: repo2

  
