name: test
on:
  workflow_call:
    inputs:
      task_definition:
        type: string
        description: 'aws task'
        required: true
      cluster:
        description: 'aws cluster'
        type: string
        required: true
      token: 
       description: 'aws cluster'
       type: string
       required: true


permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume:  arn:aws:iam::637423372838:role/aravind15b_oidc
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: launch
        uses: geekcell/github-action-aws-ecs-run-task@v3.0.0
        with:
          cluster: ${{ inputs.cluster }}
          task-definition: ${{ inputs.task_definition }}
          assign-public-ip: 'ENABLED'
          override-container: selfhosted
          subnet-ids: |
            subnet-0d19578bca5c64c0b

          override-container-environment: |
               REPO=${{ github.event.repository.name }}   
  
          security-group-ids: |
            sg-01ae387b5b393c116
      # - name: Provide a self-hosted runner to execute this job
      #   uses: PasseiDireto/gh-runner-task-action@v2.1.2
      #   with:
      #     github_pat: ${{ inputs.github_pat }}
      #     task_definition: ${{ inputs.task_definition }}
      #     cluster: ${{ inputs.cluster }}
      #     task_params_file: ${{ inputs.task-params }}
      #     network-configuration: |
      #           awsvpcConfiguration={
      #             subnets=[subnet-12345678],
      #             securityGroups=[sg-abcdef01],
      #             assignPublicIp=ENABLED
      #           }

  execute_tests:
        runs-on: ${{ github.event.repository.name }}
        name: execute test cases
        steps:
          - name: test
            run: echo test
            
          # remove the runner
          - name: remove runner
            run: |
             reg_token=$(curl -sx post -h "authorization: bearer "${{ inputs.token }}""  -h "accept: application/vnd.github+json" -h "x-github-api-version: 2022-11-28" https://api.github.com/repos/americanchemicalsociety/${{ github.event.repository.name }}/actions/runners/registration-token | jq .token --raw-output)
             cd /home/docker/actions-runner
             rm -rf .runner 
             ./config.sh remove --token $reg_token
            if: always() 
